---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

**The Coronavirus Dashboard: the case of the Netherlands**

This dashboard provides an overview of the 2019 Novel Coronavirus COVID-19 (2019-nCoV) epidemic for the Netherlands. It is built with R using the R Makrdown framework and was adapted from [The Coronavirus Dashboard: the case of Belgium](https://github.com/AntoineSoetewey/coronavirus_dashboard) by Antoine Soetewey, which is an adaptation of the original [dashboard](https://ramikrispin.github.io/coronavirus_dashboard/){target="_blank"} by Rami Krispin.

**Code**

The code behind this dashboard is available on [GitHub](https://github.com/pjastam/coronavirus_dashboard){target="_blank"}.

**Data**

The input data for this dashboard is from the [`{coronavirus}`](https://github.com/RamiKrispin/coronavirus){target="_blank"} R package. The data and dashboard are refreshed on a daily basis. The raw data is pulled from the Johns Hopkins University Center for Systems Science and Engineering (JHU CCSE) Coronavirus [repository](https://github.com/RamiKrispin/coronavirus-csv){target="_blank"}.

**Contact**

For any question or feedback, you can contact me at my GitHub mail address or send me a direct message on Twitter @pjastam. More information about this dashboard can be found in this [article](https://www.statsandr.com/blog/how-to-create-a-simple-coronavirus-dashboard-specific-to-your-country-in-r/).

**Update**

The dashboard has been updated on `r format(Sys.time(), "%A %B %d, %Y")`.